import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { Menu, X, Moon, Sun } from "lucide-react";
import { Link } from "react-router-dom";
import { useTheme } from "@store/themeStore";
export default function Navbar() {
    const [isOpen, setIsOpen] = useState(false);
    const { isDark, toggleTheme } = useTheme();
    return (_jsx("nav", { className: "sticky top-0 z-50 glass-dark border-b border-slate-700/50", children: _jsxs("div", { className: "container mx-auto px-4", children: [_jsxs("div", { className: "flex justify-between items-center h-16", children: [_jsxs(Link, { to: "/", className: "flex items-center gap-2 group", children: [_jsx("div", { className: "w-8 h-8 bg-gradient-to-br from-blue-400 to-cyan-500 rounded-lg flex items-center justify-center font-bold text-white", children: "AV" }), _jsx("span", { className: "font-bold text-xl bg-gradient-to-r from-blue-400 to-cyan-400 bg-clip-text text-transparent group-hover:from-blue-300 group-hover:to-cyan-300 transition", children: "AlgoVisual" })] }), _jsxs("div", { className: "hidden md:flex items-center gap-1", children: [_jsx(Link, { to: "/", className: "px-3 py-2 rounded-lg text-sm font-medium hover:bg-slate-700/50 transition", children: "Home" }), _jsx(Link, { to: "/learn/array", className: "px-3 py-2 rounded-lg text-sm font-medium hover:bg-slate-700/50 transition", children: "Learn" }), _jsx(Link, { to: "/visualize/array", className: "px-3 py-2 rounded-lg text-sm font-medium hover:bg-slate-700/50 transition", children: "Visualize" }), _jsx("div", { className: "border-l border-slate-700 mx-2" }), _jsx("button", { onClick: toggleTheme, className: "p-2 rounded-lg hover:bg-slate-700/50 transition", "aria-label": "Toggle theme", children: isDark ? _jsx(Sun, { size: 20 }) : _jsx(Moon, { size: 20 }) })] }), _jsxs("div", { className: "md:hidden flex items-center gap-2", children: [_jsx("button", { onClick: toggleTheme, className: "p-2 rounded-lg hover:bg-slate-700/50 transition", "aria-label": "Toggle theme", children: isDark ? _jsx(Sun, { size: 20 }) : _jsx(Moon, { size: 20 }) }), _jsx("button", { onClick: () => setIsOpen(!isOpen), className: "p-2 rounded-lg hover:bg-slate-700/50 transition", "aria-label": "Toggle menu", children: isOpen ? _jsx(X, { size: 24 }) : _jsx(Menu, { size: 24 }) })] })] }), isOpen && (_jsx("div", { className: "md:hidden border-t border-slate-700/50", children: _jsxs("div", { className: "px-4 py-2 space-y-1", children: [_jsx(Link, { to: "/", className: "block px-3 py-2 rounded-lg hover:bg-slate-700/50 transition", onClick: () => setIsOpen(false), children: "Home" }), _jsx(Link, { to: "/learn/array", className: "block px-3 py-2 rounded-lg hover:bg-slate-700/50 transition", onClick: () => setIsOpen(false), children: "Learn" }), _jsx(Link, { to: "/visualize/array", className: "block px-3 py-2 rounded-lg hover:bg-slate-700/50 transition", onClick: () => setIsOpen(false), children: "Visualize" })] }) }))] }) }));
}
