import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import { Play, Pause, RotateCcw, ChevronLeft, ChevronRight, Zap } from "lucide-react";
export default function PlaybackControls({ isAnimating, onPlay, onPause, onReset, speed, onSpeedChange, onUndo, onRedo, canUndo, canRedo, onPreviousStep, onNextStep, canPreviousStep = true, canNextStep = true, showStepControls = false, }) {
    return (_jsxs(motion.div, { initial: { opacity: 0, y: 10 }, animate: { opacity: 1, y: 0 }, className: "glass-dark p-6 rounded-xl space-y-5 bg-gradient-to-br from-slate-800/60 to-slate-900/40 border border-slate-700/50 backdrop-blur-md shadow-xl", children: [_jsxs("div", { className: "space-y-3", children: [_jsx("label", { className: "text-xs font-bold text-slate-400 uppercase tracking-widest", children: "Playback" }), _jsxs("div", { className: "flex items-center justify-center gap-3", children: [_jsx(motion.button, { whileHover: { scale: 1.08 }, whileTap: { scale: 0.95 }, onClick: isAnimating ? onPause : onPlay, className: `relative p-4 rounded-full font-semibold transition-all duration-300 flex items-center justify-center ${isAnimating
                                    ? "bg-gradient-to-r from-red-500 to-red-600 text-white shadow-lg shadow-red-500/50"
                                    : "bg-gradient-to-r from-green-500 to-emerald-600 text-white shadow-lg shadow-green-500/50"}`, "aria-label": isAnimating ? "Pause" : "Play", children: isAnimating ? _jsx(Pause, { size: 22 }) : _jsx(Play, { size: 22 }) }), _jsx(motion.button, { whileHover: { scale: 1.08, rotate: 180 }, whileTap: { scale: 0.95 }, onClick: onReset, className: "p-4 rounded-full bg-slate-700/60 hover:bg-slate-700 text-slate-200 hover:text-blue-400 transition-all duration-300 border border-slate-600/50 hover:border-blue-500/50", "aria-label": "Reset", title: "Reset to initial state", children: _jsx(RotateCcw, { size: 20 }) }), _jsx("div", { className: "border-l border-slate-600/50 h-8" }), _jsx(motion.button, { whileHover: { scale: 1.08 }, whileTap: { scale: 0.95 }, onClick: onUndo, disabled: !canUndo, className: `p-4 rounded-full font-semibold transition-all duration-300 border border-slate-600/50 ${canUndo
                                    ? "bg-slate-700/60 hover:bg-slate-700 text-slate-200 hover:text-cyan-400 hover:border-cyan-500/50 cursor-pointer"
                                    : "bg-slate-800/40 text-slate-600 cursor-not-allowed opacity-50"}`, "aria-label": "Undo", title: "Undo previous operation", children: "\u21B6" }), _jsx(motion.button, { whileHover: { scale: 1.08 }, whileTap: { scale: 0.95 }, onClick: onRedo, disabled: !canRedo, className: `p-4 rounded-full font-semibold transition-all duration-300 border border-slate-600/50 ${canRedo
                                    ? "bg-slate-700/60 hover:bg-slate-700 text-slate-200 hover:text-cyan-400 hover:border-cyan-500/50 cursor-pointer"
                                    : "bg-slate-800/40 text-slate-600 cursor-not-allowed opacity-50"}`, "aria-label": "Redo", title: "Redo next operation", children: "\u21B7" })] })] }), showStepControls && (onPreviousStep || onNextStep) && (_jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, className: "space-y-3 pt-4 border-t border-slate-700/50", children: [_jsx("label", { className: "text-xs font-bold text-slate-400 uppercase tracking-widest", children: "Algorithm Steps" }), _jsxs("div", { className: "flex items-center justify-center gap-3", children: [_jsx(motion.button, { whileHover: { scale: 1.08 }, whileTap: { scale: 0.95 }, onClick: onPreviousStep, disabled: !canPreviousStep, className: `p-3 rounded-lg font-semibold transition-all duration-300 border border-slate-600/50 ${canPreviousStep
                                    ? "bg-slate-700/60 hover:bg-slate-700 text-slate-200 hover:text-violet-400 hover:border-violet-500/50"
                                    : "bg-slate-800/40 text-slate-600 cursor-not-allowed opacity-50"}`, "aria-label": "Previous Step", title: "Go to previous step", children: _jsx(ChevronLeft, { size: 20 }) }), _jsx("div", { className: "flex-1 h-1.5 bg-slate-700/50 rounded-full overflow-hidden", children: _jsx(motion.div, { className: "h-full bg-gradient-to-r from-violet-500 to-purple-600", initial: { width: 0 }, animate: { width: `${canPreviousStep ? 50 : 0}%` }, transition: { duration: 0.3 } }) }), _jsx(motion.button, { whileHover: { scale: 1.08 }, whileTap: { scale: 0.95 }, onClick: onNextStep, disabled: !canNextStep, className: `p-3 rounded-lg font-semibold transition-all duration-300 border border-slate-600/50 ${canNextStep
                                    ? "bg-slate-700/60 hover:bg-slate-700 text-slate-200 hover:text-violet-400 hover:border-violet-500/50"
                                    : "bg-slate-800/40 text-slate-600 cursor-not-allowed opacity-50"}`, "aria-label": "Next Step", title: "Go to next step", children: _jsx(ChevronRight, { size: 20 }) })] })] })), _jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.1 }, className: "space-y-3 pt-4 border-t border-slate-700/50", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("label", { htmlFor: "speed", className: "flex items-center gap-2 text-xs font-bold text-slate-400 uppercase tracking-widest", children: [_jsx(Zap, { size: 14, className: "text-yellow-400" }), "Speed"] }), _jsxs(motion.span, { initial: { scale: 1.2, opacity: 0 }, animate: { scale: 1, opacity: 1 }, className: "text-sm font-bold bg-gradient-to-r from-yellow-400 to-orange-500 bg-clip-text text-transparent", children: [speed.toFixed(1), "x"] }, speed)] }), _jsxs("div", { className: "relative", children: [_jsx("input", { id: "speed", type: "range", min: "0.5", max: "2", step: "0.1", value: speed, onChange: (e) => onSpeedChange(parseFloat(e.target.value)), className: "w-full h-2 bg-gradient-to-r from-slate-700 to-slate-600 rounded-lg appearance-none cursor-pointer accent-yellow-500 transition-all", style: {
                                    backgroundImage: `linear-gradient(to right, rgb(29, 78, 139), rgb(59, 130, 246))`,
                                } }), _jsxs("div", { className: "flex justify-between text-xs text-slate-500 mt-2 px-1", children: [_jsx("span", { children: "0.5x" }), _jsx("span", { children: "1.0x" }), _jsx("span", { children: "1.5x" }), _jsx("span", { children: "2.0x" })] })] })] })] }));
}
